name: env_segmentation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.21.6
  - pandas=1.3.5
  - opencv=4.5.5
  - pydicom=2.2.2
  - scikit-image=0.19.1
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - statsmodels=0.13.2
  - tqdm=4.62.3
  - pip
  - pip:
      - tensorflow-macos==2.9.0
      - tensorflow-metal==0.5.0
      - SimpleITK==2.2.0
