name: myenv  # Nom de l'environnement
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow=2.13.0
  - keras=2.13.1
  - opencv=4.5.3
  - scikit-image=0.19.3
  - scipy=1.10.1
  - tqdm=4.66.0
  - statsmodels=0.14.0
  - matplotlib=3.7.0
  - simpleitk=2.2.1
  - numpy=1.24.3
  - h5py=3.13.0
  - pillow
  - pip
  - pip:
    - protobuf==4.25.7
    - google-auth==2.39.0
    - requests==2.32.3
    - tensorboard==2.13.0
    - grpcio==1.71.0
    - google-pasta==0.2.0
    - astunparse==1.6.3
